version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.7.1
    container_name: elasticsearch
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      - ./elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
  kibana:
    image: kibana:7.7.1
    container_name: kibana
    links:
      - elasticsearch:es
    depends_on:
      - elasticsearch
    environment:
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601
    restart: always
  logstash:
    image: logstash:7.7.1
    container_name: logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:es
    ports:
      - 5044:5044
    restart: always
  filebeat:
    image: elastic/filebeat:7.7.1
    container_name: filebeat
    links:
      - logstash:logstash
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /usr/local/logs:/var/logs/springboot
    depends_on:
      - logstash
    restart: always
