version: '3'
services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: rm-bp1cp68o8t1gq604p5o.mysql.rds.aliyuncs.com
      DB_DATABASE: keycloak
      DB_USER: zhouxinlei
      DB_PASSWORD: Zxl298828
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
      JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 80:8080
