version: '3'
services:
  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: 47.114.40.129
      DB_DATABASE: keycloak
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 123456
      JDBC_PARAMS: "connectTimeout=30000"
    ports:
      - 8760:8080
