version: '3.3'
services:
  oap:
    image: skywalking/oap
    container_name: oap
    restart: always
    ports:
      - 11801:11800
      - 12801:12800
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: 172.34.200.5:9200
  skywalking-ui:
    image: skywalking/ui
    container_name: skywalking-ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8605:8080
    environment:
      SW_OAP_ADDRESS: 172.34.200.5:12801
      collector.ribbon.listOfServers: 172.34.200.5:12801
      security.user.admin.password: 123456
