version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    volumes:
      - ./zookeeper/data:/data
      - ./zookeeper/datalog:/datalog
    ports:
      - 2181:2181
    restart: always
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zk:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${IP}:9092
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_LOG_RETENTION_HOURS=120
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DELETE_RETENTION_MS=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./kafka/data:/kafka
    restart: always
  kafka-manager-web:
    image: registry.cn-hangzhou.aliyuncs.com/sparkzxl/kafka-manager-web:2.3.0
    container_name: kafka-manager-web
    depends_on:
      - kafka
    restart: always
    environment:
      MYSQL_SERVICE_HOST: sparkzxl.mysql.rds.aliyuncs.com
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_USER: zhouxinlei
      MYSQL_SERVICE_PASSWORD: Zxl298828
      MYSQL_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    ports:
      - 8701:8080
