version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_web
    command: redis-server /etc/redis/redis.conf --appendonly yes
    privileged: true
    restart: always
    volumes:
      - ./data:/data #数据文件挂载
      - ./conf/redis.conf:/etc/redis/redis.conf
    ports:
      - 6379:6379
